#[derive(Copy, Clone, PartialEq, Debug)]
pub enum AddressMode {
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    Relative,
    Implied,
    Accumulator,
}

#[derive(Debug)]
pub enum Instruction {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
    SLO, // Start of unofficial
    RLA,
    SRE,
    RRA,
    SAX,
    LAX,
    DCP,
    ISC,
    ANC,
    ALR,
    ARR,
    XAA,
    AXS, // End of unofficial (with idea of what to do)
    XXX,
    STP, // Unknown
    AHX,
    TAS,
    LAS,
    SKB,
}

pub struct Opcode {
    pub instruction: Instruction,
    pub address_mode: AddressMode,
    pub cycles: u8,
    pub bytes: u8,
}

impl Opcode {
    pub fn new(instruction: Instruction, address_mode: AddressMode, cycles: u8, bytes: u8) -> Self {
        Opcode {
            instruction,
            address_mode,
            cycles,
            bytes,
        }
    }
}

lazy_static! {
    pub static ref CPU_OPCODES: Vec<Opcode> = vec![
        Opcode::new(Instruction::BRK, AddressMode::Implied, 7, 1),
        Opcode::new(Instruction::ORA, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SLO, AddressMode::IndirectX, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::ORA, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::ASL, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::SLO, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::PHP, AddressMode::Implied, 3, 1),
        Opcode::new(Instruction::ORA, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::ASL, AddressMode::Accumulator, 2, 1),
        Opcode::new(Instruction::ANC, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::NOP, AddressMode::Absolute, 4, 1),
        Opcode::new(Instruction::ORA, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::ASL, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::SLO, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::BPL, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::ORA, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SLO, AddressMode::IndirectY, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::ORA, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::ASL, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::SLO, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::CLC, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::ORA, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SLO, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::NOP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::ORA, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::ASL, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::SLO, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::JSR, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::AND, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::RLA, AddressMode::IndirectX, 8, 2),
        Opcode::new(Instruction::BIT, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::AND, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::ROL, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::RLA, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::PLP, AddressMode::Implied, 4, 1),
        Opcode::new(Instruction::AND, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::ROL, AddressMode::Accumulator, 2, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::BIT, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::AND, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::ROL, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::RLA, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::BMI, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::AND, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::RLA, AddressMode::IndirectY, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::AND, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::ROL, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::RLA, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::SEC, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::AND, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::RLA, AddressMode::AbsoluteY, 7, 3),
        Opcode::new(Instruction::NOP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::AND, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::ROL, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::RLA, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::RTI, AddressMode::Implied, 6, 1),
        Opcode::new(Instruction::EOR, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SRE, AddressMode::IndirectX, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::EOR, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::LSR, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::SRE, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::PHA, AddressMode::Implied, 3, 1),
        Opcode::new(Instruction::EOR, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::LSR, AddressMode::Accumulator, 2, 1),
        Opcode::new(Instruction::ALR, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::JMP, AddressMode::Absolute, 3, 3),
        Opcode::new(Instruction::EOR, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::LSR, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::SRE, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::BVC, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::EOR, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SRE, AddressMode::IndirectY, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::EOR, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::LSR, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::SRE, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::CLI, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::EOR, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SRE, AddressMode::AbsoluteY, 7, 3),
        Opcode::new(Instruction::NOP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::EOR, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::LSR, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::SRE, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::RTS, AddressMode::Implied, 6, 1),
        Opcode::new(Instruction::ADC, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::RRA, AddressMode::IndirectX, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::ADC, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::ROR, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::RRA, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::PLA, AddressMode::Implied, 4, 1),
        Opcode::new(Instruction::ADC, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::ROR, AddressMode::Accumulator, 2, 1),
        Opcode::new(Instruction::ARR, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::JMP, AddressMode::Indirect, 5, 3),
        Opcode::new(Instruction::ADC, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::ROR, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::RRA, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::BVS, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::ADC, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::RRA, AddressMode::IndirectY, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::ADC, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::ROR, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::RRA, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::SEI, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::ADC, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::RRA, AddressMode::AbsoluteY, 7, 3),
        Opcode::new(Instruction::NOP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::ADC, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::ROR, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::RRA, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::SKB, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::STA, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::SKB, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::SAX, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::STY, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::STA, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::STX, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::SAX, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::DEY, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SKB, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::TXA, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::STY, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::STA, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::STX, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::SAX, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::BCC, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::STA, AddressMode::IndirectY, 6, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 6, 1),
        Opcode::new(Instruction::STY, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::STA, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::STX, AddressMode::ZeroPageY, 4, 2),
        Opcode::new(Instruction::SAX, AddressMode::ZeroPageY, 4, 2),
        Opcode::new(Instruction::TYA, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::STA, AddressMode::AbsoluteY, 5, 3),
        Opcode::new(Instruction::TXS, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 5, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 5, 1),
        Opcode::new(Instruction::STA, AddressMode::AbsoluteX, 5, 3),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 5, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 5, 1),
        Opcode::new(Instruction::LDY, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::LDA, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::LDX, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::LAX, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::LDY, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::LDA, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::LDX, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::LAX, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::TAY, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::LDA, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::TAX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::LDY, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::LDA, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::LDX, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::LAX, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::BCS, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::LDA, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::LAX, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::LDY, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::LDA, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::LDX, AddressMode::ZeroPageY, 4, 2),
        Opcode::new(Instruction::LAX, AddressMode::ZeroPageY, 4, 2),
        Opcode::new(Instruction::CLV, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::LDA, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::TSX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 4, 1),
        Opcode::new(Instruction::LDY, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::LDA, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::LDX, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::LAX, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::CPY, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::CMP, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::SKB, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::DCP, AddressMode::IndirectX, 8, 2),
        Opcode::new(Instruction::CPY, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::CMP, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::DEC, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::DCP, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::INY, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::CMP, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::DEX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::AXS, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::CPY, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::CMP, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::DEC, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::DCP, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::BNE, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::CMP, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::DCP, AddressMode::IndirectY, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::CMP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::DEC, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::DCP, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::CLD, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::CMP, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::DCP, AddressMode::AbsoluteY, 7, 3),
        Opcode::new(Instruction::NOP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::CMP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::DEC, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::DCP, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::CPX, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::SBC, AddressMode::IndirectX, 6, 2),
        Opcode::new(Instruction::SKB, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::ISC, AddressMode::IndirectX, 8, 1),
        Opcode::new(Instruction::CPX, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::SBC, AddressMode::ZeroPage, 3, 2),
        Opcode::new(Instruction::INC, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::ISC, AddressMode::ZeroPage, 5, 2),
        Opcode::new(Instruction::INX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SBC, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SBC, AddressMode::Immediate, 2, 2),
        Opcode::new(Instruction::CPX, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::SBC, AddressMode::Absolute, 4, 3),
        Opcode::new(Instruction::INC, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::ISC, AddressMode::Absolute, 6, 3),
        Opcode::new(Instruction::BEQ, AddressMode::Relative, 2, 2),
        Opcode::new(Instruction::SBC, AddressMode::IndirectY, 5, 2),
        Opcode::new(Instruction::XXX, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::ISC, AddressMode::IndirectY, 8, 2),
        Opcode::new(Instruction::NOP, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::SBC, AddressMode::ZeroPageX, 4, 2),
        Opcode::new(Instruction::INC, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::ISC, AddressMode::ZeroPageX, 6, 2),
        Opcode::new(Instruction::SED, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::SBC, AddressMode::AbsoluteY, 4, 3),
        Opcode::new(Instruction::NOP, AddressMode::Implied, 2, 1),
        Opcode::new(Instruction::ISC, AddressMode::AbsoluteY, 7, 3),
        Opcode::new(Instruction::NOP, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::SBC, AddressMode::AbsoluteX, 4, 3),
        Opcode::new(Instruction::INC, AddressMode::AbsoluteX, 7, 3),
        Opcode::new(Instruction::ISC, AddressMode::AbsoluteX, 7, 3)
    ];
}
