#[derive(Copy, Clone, PartialEq, Debug)]
pub enum AddressMode {
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    Relative,
    Implied,
    Accumulator,
}

#[derive(Debug)]
pub enum Opcode {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
    SLO, // Start of unofficial
    RLA,
    SRE,
    RRA,
    SAX,
    LAX,
    DCP,
    ISC,
    ANC,
    ALR,
    ARR,
    XAA,
    AXS, // End of unofficial (with idea of what to do)
    XXX,
    STP, // Unknown
    AHX,
    TAS,
    LAS,
    SKB,
}

pub struct Instruction {
    pub instruction: Opcode,
    pub address_mode: AddressMode,
    pub cycles: u8,
    pub bytes: u8,
}

impl Instruction {
    pub fn new(instruction: Opcode, address_mode: AddressMode, cycles: u8, bytes: u8) -> Self {
        Instruction { instruction, address_mode, cycles, bytes }
    }
}

lazy_static! {
    pub static ref CPU_OPCODES: Vec<Instruction> = vec![
        Instruction::new(Opcode::BRK, AddressMode::Implied, 7, 1),
        Instruction::new(Opcode::ORA, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SLO, AddressMode::IndirectX, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::ORA, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::ASL, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::SLO, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::PHP, AddressMode::Implied, 3, 1),
        Instruction::new(Opcode::ORA, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::ASL, AddressMode::Accumulator, 2, 1),
        Instruction::new(Opcode::ANC, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::NOP, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::ORA, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::ASL, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::SLO, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::BPL, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::ORA, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SLO, AddressMode::IndirectY, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::ORA, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::ASL, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::SLO, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::CLC, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::ORA, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SLO, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::NOP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::ORA, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::ASL, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::SLO, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::JSR, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::AND, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::RLA, AddressMode::IndirectX, 8, 2),
        Instruction::new(Opcode::BIT, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::AND, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::ROL, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::RLA, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::PLP, AddressMode::Implied, 4, 1),
        Instruction::new(Opcode::AND, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::ROL, AddressMode::Accumulator, 2, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::BIT, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::AND, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::ROL, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::RLA, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::BMI, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::AND, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::RLA, AddressMode::IndirectY, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::AND, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::ROL, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::RLA, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::SEC, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::AND, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::RLA, AddressMode::AbsoluteY, 7, 3),
        Instruction::new(Opcode::NOP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::AND, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::ROL, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::RLA, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::RTI, AddressMode::Implied, 6, 1),
        Instruction::new(Opcode::EOR, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SRE, AddressMode::IndirectX, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::EOR, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::LSR, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::SRE, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::PHA, AddressMode::Implied, 3, 1),
        Instruction::new(Opcode::EOR, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::LSR, AddressMode::Accumulator, 2, 1),
        Instruction::new(Opcode::ALR, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::JMP, AddressMode::Absolute, 3, 3),
        Instruction::new(Opcode::EOR, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::LSR, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::SRE, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::BVC, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::EOR, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SRE, AddressMode::IndirectY, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::EOR, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::LSR, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::SRE, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::CLI, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::EOR, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SRE, AddressMode::AbsoluteY, 7, 3),
        Instruction::new(Opcode::NOP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::EOR, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::LSR, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::SRE, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::RTS, AddressMode::Implied, 6, 1),
        Instruction::new(Opcode::ADC, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::RRA, AddressMode::IndirectX, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::ADC, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::ROR, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::RRA, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::PLA, AddressMode::Implied, 4, 1),
        Instruction::new(Opcode::ADC, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::ROR, AddressMode::Accumulator, 2, 1),
        Instruction::new(Opcode::ARR, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::JMP, AddressMode::Indirect, 5, 3),
        Instruction::new(Opcode::ADC, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::ROR, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::RRA, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::BVS, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::ADC, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::RRA, AddressMode::IndirectY, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::ADC, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::ROR, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::RRA, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::SEI, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::ADC, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::RRA, AddressMode::AbsoluteY, 7, 3),
        Instruction::new(Opcode::NOP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::ADC, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::ROR, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::RRA, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::SKB, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::STA, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::SKB, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::SAX, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::STY, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::STA, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::STX, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::SAX, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::DEY, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SKB, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::TXA, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::STY, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::STA, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::STX, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::SAX, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::BCC, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::STA, AddressMode::IndirectY, 6, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 6, 1),
        Instruction::new(Opcode::STY, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::STA, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::STX, AddressMode::ZeroPageY, 4, 2),
        Instruction::new(Opcode::SAX, AddressMode::ZeroPageY, 4, 2),
        Instruction::new(Opcode::TYA, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::STA, AddressMode::AbsoluteY, 5, 3),
        Instruction::new(Opcode::TXS, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 5, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 5, 1),
        Instruction::new(Opcode::STA, AddressMode::AbsoluteX, 5, 3),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 5, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 5, 1),
        Instruction::new(Opcode::LDY, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::LDA, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::LDX, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::LAX, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::LDY, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::LDA, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::LDX, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::LAX, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::TAY, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::LDA, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::TAX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::LDY, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::LDA, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::LDX, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::LAX, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::BCS, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::LDA, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::LAX, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::LDY, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::LDA, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::LDX, AddressMode::ZeroPageY, 4, 2),
        Instruction::new(Opcode::LAX, AddressMode::ZeroPageY, 4, 2),
        Instruction::new(Opcode::CLV, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::LDA, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::TSX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 4, 1),
        Instruction::new(Opcode::LDY, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::LDA, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::LDX, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::LAX, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::CPY, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::CMP, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::SKB, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::DCP, AddressMode::IndirectX, 8, 2),
        Instruction::new(Opcode::CPY, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::CMP, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::DEC, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::DCP, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::INY, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::CMP, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::DEX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::AXS, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::CPY, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::CMP, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::DEC, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::DCP, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::BNE, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::CMP, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::DCP, AddressMode::IndirectY, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::CMP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::DEC, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::DCP, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::CLD, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::CMP, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::DCP, AddressMode::AbsoluteY, 7, 3),
        Instruction::new(Opcode::NOP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::CMP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::DEC, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::DCP, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::CPX, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::SBC, AddressMode::IndirectX, 6, 2),
        Instruction::new(Opcode::SKB, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::ISC, AddressMode::IndirectX, 8, 2),
        Instruction::new(Opcode::CPX, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::SBC, AddressMode::ZeroPage, 3, 2),
        Instruction::new(Opcode::INC, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::ISC, AddressMode::ZeroPage, 5, 2),
        Instruction::new(Opcode::INX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SBC, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SBC, AddressMode::Immediate, 2, 2),
        Instruction::new(Opcode::CPX, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::SBC, AddressMode::Absolute, 4, 3),
        Instruction::new(Opcode::INC, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::ISC, AddressMode::Absolute, 6, 3),
        Instruction::new(Opcode::BEQ, AddressMode::Relative, 2, 2),
        Instruction::new(Opcode::SBC, AddressMode::IndirectY, 5, 2),
        Instruction::new(Opcode::XXX, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::ISC, AddressMode::IndirectY, 8, 2),
        Instruction::new(Opcode::NOP, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::SBC, AddressMode::ZeroPageX, 4, 2),
        Instruction::new(Opcode::INC, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::ISC, AddressMode::ZeroPageX, 6, 2),
        Instruction::new(Opcode::SED, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::SBC, AddressMode::AbsoluteY, 4, 3),
        Instruction::new(Opcode::NOP, AddressMode::Implied, 2, 1),
        Instruction::new(Opcode::ISC, AddressMode::AbsoluteY, 7, 3),
        Instruction::new(Opcode::NOP, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::SBC, AddressMode::AbsoluteX, 4, 3),
        Instruction::new(Opcode::INC, AddressMode::AbsoluteX, 7, 3),
        Instruction::new(Opcode::ISC, AddressMode::AbsoluteX, 7, 3)
    ];
}
